### ISSUE TITLE
create .fst versions of files and load these?

### ISSUE THREAD

**Issue by MattCowgill** [grattan/grattandata#20]
This could work like:

- When `read_microdata()` is passed a (single) valid filename fragment, it checks to see if there is a .fst file with the same basename in that folder. 

- If a .fst file is found, it loads this. If an .fst file isn't found, it loads the requested file (.csv, .dta, whatever) and writes an .fst file, so that there will be one available next time.

Users wouldn't need to know this was going on. 

Benefit: speed. Loading the 2017-18 SIH income unit file takes 0.27 seconds when reading `.dta` and 0.03 seconds from `.fst`.

Cost: Code becomes slightly more elaborate under the hood. Extra storage on Dropbox is used (minimal, as .fst is compressed; I don't think this is a big issue). I'm not sure about the preservation of attributes (eg. labels), which could be a dealbreaker.

**Comment by MattCowgill** [comment]
The more I think about this the more I'm leaning against it.

**Comment by MattCowgill** [comment]
DECISION: do the `.fst` thing, but make it optional; by default `read_microdata()` will return the file that a user requests

**Comment by wfmackey** [comment]
great decision @MattCowgill

**Comment by HughParsonage** [comment]
On the matter of label-preservation, `.fst` won't preserve all labels and classes. However, (a) most classes will be, (b) esoteric classes are probably best avoided, and (c) if the class isn't supported but is relatively common, Marcus will probably add it if you ask. 

Speed is the main benefit of .fst but a close second is random access. Very rarely do I need to know the [age of the 20th person in the household](https://www.online.fbe.unimelb.edu.au/HILDAodd/srchVarnameUsingCategoriesCrossWave.aspx), but with most file types I have to read it if I want any other column from that set. Relatedly, there may be cases where it is worth preparing an enormous, derived/modelled/combined table but where the table requires a big machine to prepare or access in its entirety. With an fst file, analysts with only 64 GB of RAM (or less) can still use it by selecting only the columns they need. This can make it easier to work as a team on large or complex analysis where different members have different specs.

**Comment by MattCowgill** [comment]
Thanks @HughParsonage. I ended up adding an argument to the `read_microdata()` function: `fast = FALSE`. If set to `TRUE`, it looks for a file with the same basename and location as the requested file, with an `.fst` extension. If found, it reads it. 

I think that including this argument, but making it `FALSE` by default, gets the balance right for users at Grattan. It means that anyone requesting a `.dta` file or similar gets what they asked for, but if they want it they can get the `.fst` instead with all the benefits that brings.
