### ISSUE TITLE
Make package more generalisable

### ISSUE THREAD

**Issue by jonathananolan** [grattan/grattandata#21]
How would you feel about me making a fork and making this more generalisable outside Grattan? 

I was thinking two more arguments: 
`
dropbox = TRUE
`
If true, package will act as currently,

`
data_warehouse_dir = "data/microdata"
`

Path to subfolder within dropbox, or other working directory if dropbox = FALSE. 

Only issue I can think of is whether supplying "data/microdata" as an argument will create OS compatibility issues.

**Comment by MattCowgill** [comment]
I can't see why it would be useful outside Grattan, but sure, go for it.

You can use the base function `file.path()` to construct platform-independent file paths, eg.:

![Screen Shot 2019-11-26 at 8 31 22 am](https://user-images.githubusercontent.com/8002951/69579707-27757700-1027-11ea-8bc9-710f91eb68fe.png)

You can use it in combination with `grattandata::get_dropbox_location()` to specify the full path to the data folder, as in:

![Screen Shot 2019-11-26 at 8 30 31 am](https://user-images.githubusercontent.com/8002951/69579740-39571a00-1027-11ea-84c3-51c3a0ac1a0a.png)
