### ISSUE TITLE
add function to access non-shared microdata

### ISSUE THREAD

**Issue by MattCowgill** [grattan/grattandata#26]
eg. HILDA.

Current thought: add a function (`set_hilda_location()` or `set_private_data_location()`) or something. You'd use it this like:

```
set_hilda_location("/Users/mcowgill/documents/HILDA")
```

When the HILDA location (or private microdata location) has been set, `read_microdata()` will look in there as well as in the regular Dropbox for to match the filename you supply

The benefits of this are:
1. Once the user has set this location in an R session, they can then just use the filenames in `read_microdata()` without worrying about the file path again
2. This makes scripts more shareable. Nothing would need to change in a script when it's shared other than the path in `set_hilda_location()` or whatever

Thoughts @jonathananolan @wfmackey ?

**Comment by MattCowgill** [comment]
Open to other ideas also

**Comment by MattCowgill** [comment]
I still think this is a good idea, but it's unclear if it's worth doing

**Comment by jonathananolan** [comment]
Given ASD is no longer certifying cloud providers, perhaps we should contact the ADA and ask them to update their guidelines in a way that allows us to use DropBox? Dropbox can now store data in Australia which was the main hurdle for DropBox accreditation. 

https://www.cyber.gov.au/acsc/view-all-content/programs/irap/asd-certified-cloud-services

**Comment by MattCowgill** [comment]
I'm going to add a function to do this - `add_microdata_location()`. 

Someone in the future can maybe follow up with ADA about possible storage of HILDA on Dropbox.
